# Site settings
title: Axu Blog
SEOTitle: 阿许的博客 | Axu Blog
header-img: img/107830-106.webp
email: gj-x@qq.com
description: "No Pain No Gain."
keyword: "Axu, Axu Blog, 阿许的博客, xuguojing, 许国境, iOS, Apple, ,Android, iPhone, OnePlus One"
url: "http://xuguojingcode.github.io"          # your host, for absolute URL
baseurl: ""      # for example, '/blog' if your blog hosted on 'host/blog'
github_repo: "https://github.com/xuguojingcode.github.io.git" # you code repository

# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "No Pain No Gain No $$!!"
sidebar-avatar: /img/designer-pic.jpg      # use absolute URL, seeing it's used in both `/` and `/about/`



# SNS settings
RSS: false
# weibo_username:     qiubaiying
zhihu_username:     MrError
#github_username:    xuguojingcode
#facebook_username:  xuguojing
#jianshu_username:   e71990ada2fd
#twitter_username:   qiubaiying




# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`



# Gems
# from PR#40, to support local preview for Jekyll 3.0
gems: [jekyll-paginate]



# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM                            # use Github Flavored Markdown !important



# 评论系统
#Disqus settings（https://disqus.com/）
#disqus_username: xuguojing

# 多说 将于2017年6月1日正式关停服务，建议使用 Disqus（http://dev.duoshuo.com/threads/58d1169ae293b89a20c57241）
# Duoshuo settings
# duoshuo_username: qiubaiying
# Share component is depend on Comment so we can NOT use share only.
# duoshuo_share: true                     # set to false if you want to use Comment without Sharing


# Gitalk
gitalk:
  enable: true    #是否开启Gitalk评论
  clientID: 2b1efbca26be113cfef5   #生成的clientID
  clientSecret: ed31379257e47db54d5221dac7ed871f503ddec4  #同上
  repo: XuguojingCode.github.io    #仓库名称
  owner: XuguojingCode    #github用户名
  admin: XuguojingCode
  distractionFreeMode: true #是否启用类似FB的阴影遮罩


# Analytics settings
# Baidu Analytics
ba_track_id: eee1f44e081325f9547015282f2fefe1

 #Google Analytics
ga_track_id: 'UA-110582355-1'            # Format: UA-xxxxxx-xx
ga_domain: auto





# Featured Tags
featured-tags: true                     # 是否使用首页标签
featured-condition-size: 0              # 相同标签数量大于这个数，才会出现在首页



# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true



# Friends
friends: [
    {
        title: "R2Beat",
        href: "http://r2.qq.com"
    },{
        title: "Xda·gj",
        href: "https://forum.xda-developers.com/"
    },{
        title: "Apple",
        href: "https://apple.com"
    },{
        title: "Apple Developer",
        href: "https://developer.apple.com/"
    }
]
